### ISSUE TITLE
更换driver.get的页面后，修改完一些元素的读取，启动main.py后报了一个错：“selenium.common.exceptions.WebDriverException: Message: no such execution context: loader has changed while resolving nodes“”

### ISSUE THREAD

**Issue by Arvin225** [zdjzce923/automate-boss#1]
我想从选择了职位后的页面开始运行，代码中便修改了`driver.get('')`中的网址为目标页面的地址，相应地也修改了元素的位置：
```python
def communicate(driver):

    read_more = driver.find_element(By.XPATH, '//*[@id="main"]/div/div')
    while not elementHasClass(read_more, 'disabled'):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
        time.sleep(2)

    time.sleep(2)
    jd_list = driver.find_element(By.XPATH, '//*[@id="main"]/div/ul')
```
启动后报了这么一个错误：
selenium.common.exceptions.WebDriverException: Message: no such execution context: loader has changed while resolving nodes
  (Session info: chrome=113.0.5672.93)

是否还有哪里要做修改呢？

**Comment by moksha-z** [comment]
> 我想从选择了职位后的页面开始运行，代码中便修改了`driver.get('')`中的网址为目标页面的地址，相应地也修改了元素的位置：
> 
> ```python
> def communicate(driver):
> 
>     read_more = driver.find_element(By.XPATH, '//*[@id="main"]/div/div')
>     while not elementHasClass(read_more, 'disabled'):
>         driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
>         time.sleep(2)
> 
>     time.sleep(2)
>     jd_list = driver.find_element(By.XPATH, '//*[@id="main"]/div/ul')
> ```
> 
> 启动后报了这么一个错误： selenium.common.exceptions.WebDriverException: Message: no such execution context: loader has changed while resolving nodes (Session info: chrome=113.0.5672.93)
> 
> 是否还有哪里要做修改呢？

抱歉 之前一直没有看 issues, 打算迁移到 Electron 客户端了，旧的 Python 脚本容错率太低不维护了。
